import { EsjOptions } from '../../interfaces/esj-options.js';

export function createHtmlHintConfig(options: EsjOptions): unknown {
  const config = {
    'alt-require': true,
    'attr-lowercase': true,
    'attr-no-duplication': true,
    'attr-no-unnecessary-whitespace': true,
    'attr-sorted': true,
    'attr-unsafe-chars': true,
    'attr-value-double-quotes': true,
    'attr-value-no-duplication': true,
    'attr-value-not-empty': true,
    'attr-value-single-quotes': true,
    'attr-whitespace': true,
    'button-type-require': true,
    'doctype-first': true,
    'doctype-html5': true,
    'empty-tag-not-self-closed': true,
    'form-method-require': true,
    'frame-title-require': true,
    'h1-require': true,
    'head-script-disabled': true,
    'href-abs-or-rel': true,
    'html-lang-require': true,
    'id-class-ad-disabled': true,
    'id-class-value': true,
    'id-unique': true,
    'inline-script-disabled': true,
    'inline-style-disabled': true,
    'input-requires-label': true,
    'link-rel-canonical-require': true,
    'main-require': true,
    'meta-charset-require': true,
    'meta-description-require': true,
    'meta-viewport-require': true,
    'script-disabled': true,
    'space-tab-mixed-disabled': true,
    'spec-char-escape': true,
    'src-not-empty': true,
    'style-disabled': true,
    'tag-no-obsolete': true,
    'tag-pair': true,
    'tag-self-close': true,
    'tagname-lowercase': true,
    'tagname-specialchars': true,
    'tags-check': true,
    'title-require': true,
  };

  return config;
}
