export enum Tools {
  Jest = 'Jest',
  Husky = 'Husky',
  EsLint = 'eslint',
  Prettier = 'Prettier',
  Tailwind = 'Tailwind',
  HTMLHint = 'HTMLhint',
  Stylelint = 'Stylelint',
  TypeScript = 'TypeScript',
  EditorConfig = 'EditorConfig',
  MarkdownLint = 'MarkdownLint',
  LintStaged = 'LintStaged',
  OxFmt = 'OxFmt',
  OxLint = 'OxLint',
  CommitLint = 'CommitLint',
}
